# Data Loading Notebook

This notebook covers loading and displaying basic information about the raw dataset scraped from TW's website.

## Table of Contents

1. [Load data](#Load-data)
2. [Examine each column](#Examine-each-column)
3. [Filter out junior racquets](#filter-out-junior-racquets)
4. [Takeaways and next steps](#takeaways-and-next-steps)

In [47]:
# Import all packages here
import pandas as pd
import numpy as np
from pathlib import Path

## Load data

In [14]:
# Define data directory path and load data- assuming you're in notebooks/
DATA_DIR = Path().cwd().parent / "data"
raw_df = pd.read_csv(DATA_DIR / "raw" / "racquets_raw_02_14_26.csv")

In [15]:
raw_df.head()

,racquet_url,racquet_img,racquet_name,racquet_rating,racquet_price,racquet_description,head_size,length,strung_weight,balance,...,racquet_colors,grip_type,string_pattern,string_tension,age,weight,height,other,age_9-10,strung _weight
0,https://www.tennis-warehouse.com/Babolat_Pure_...,https://img.tennis-warehouse.com/watermark/rs....,Babolat Pure Aero 2026,NaN,299.0,Engineered for speed. With its fabled combinat...,100 in² / 645.16 cm²,27in / 68.58cm,11.2oz / 318g,12.99in / 32.99cm / 4 pts HL,...,Yellow/Black,Babolat Syntec Pro,"16 Mains / 19 Crosses Mains skip: 8T,8H Two Pi...",46-55 pounds,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.tennis-warehouse.com/Babolat_Pure_...,https://img.tennis-warehouse.com/watermark/rs....,Babolat Pure Aero 98 2026,4.3,309.0,Speed. Spin. Accuracy. Featuring the smallest ...,98 in² / 632.26 cm²,27in / 68.58cm,11.4oz / 323g,12.79in / 32.49cm / 6 pts HL,...,Grey/Yellow,Syntec Pro,"16 Mains / 20 Crosses Mains skip: 7T,9T,7H,9H ...",46-55 pounds,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.tennis-warehouse.com/Babolat_Pure_...,https://img.tennis-warehouse.com/watermark/rs....,Babolat Pure Aero 98 2-Pack 2026,NaN,599.0,The most surgical member of the Pure Aero fami...,98 in² / 632.26 cm²,27in / 68.58cm,11.4oz / 323g,12.79in / 32.49cm / 6 pts HL,...,Black/Yellow,Syntec Pro,"16 Mains / 20 Crosses Mains skip: 7T,9T,7H,9H ...",46-55 pounds,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.tennis-warehouse.com/Babolat_Pure_...,https://img.tennis-warehouse.com/watermark/rs....,Babolat Pure Aero Plus 2026,NaN,299.0,One of the games most powerful and spin-friend...,100 in² / 645.16 cm²,27.5in / 69.85cm,11.3oz / 320g,12.99in / 32.99cm / 6 pts HL,...,Grey/Yellow,Babolat Syntec Pro,"16 Mains / 19 Crosses Mains skip: 8T,8H Two Pi...",46-55 pounds,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.tennis-warehouse.com/Babolat_Pure_...,https://img.tennis-warehouse.com/watermark/rs....,Babolat Pure Aero Team 2026,NaN,279.0,Updated with improved aerodynamics and better ...,100 in² / 645.16 cm²,27in / 68.58cm,10.6oz / 301g,13in / 33.02cm / 4 pts HL,...,Grey/Yellow,Babolat Syntec Pro,"16 Mains / 19 Crosses Mains skip: 7T,9T,7H,9H ...",44-53 pounds,NaN,NaN,NaN,NaN,NaN,NaN

**It might be good to extract the racquet brand name for metadata & filtering in the search workflow.**

Below, I'll look at the shape and columns of the df. It has 398 rows and 37 columns. The additional columns are likely extraneuous "spec" columns that got appended for niche, junior, or special racquets. **The best approach seem to be to just remove these columns as they don't convey useful information for most racquets**.

In [11]:
raw_df.shape

(398, 27)

In [12]:
raw_df.columns

Index(['racquet_url', 'racquet_img', 'racquet_name', 'racquet_rating',
       'racquet_price', 'racquet_description', 'head_size', 'length',
       'strung_weight', 'balance', 'swingweight', 'stiffness', 'beam_width',
       'composition', 'power_level', 'stroke_style', 'swing_speed',
       'racquet_colors', 'grip_type', 'string_pattern', 'string_tension',
       'age', 'weight', 'height', 'other', 'age_9-10', 'strung _weight'],
      dtype='str')

Below is a list of each column, it's non-null count, and its data type. The last couple columns are almost entirely NA. There were also clearly some non-standard racquet pages within the brand pages as there are 14 "racquets" that do not have names but that had functioning links. 

**Before doing any further cleaning, I will need to filter for racquets that have a name**.

In [10]:
raw_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   racquet_url          398 non-null    str
 1   racquet_img          384 non-null    str
 2   racquet_name         384 non-null    str
 3   racquet_rating       264 non-null    float64
 4   racquet_price        384 non-null    float64
 5   racquet_description  370 non-null    str
 6   head_size            354 non-null    str
 7   length               354 non-null    str
 8   strung_weight        304 non-null    str
 9   balance              306 non-null    str
 10  swingweight          306 non-null    float64
 11  stiffness            305 non-null    str
 12  beam_width           306 non-null    str
 13  composition          354 non-null    str
 14  power_level          306 non-null    str
 15  stroke_style         306 non-null    str
 16  swing_speed          306 non-null    str
 17  racquet_colors       346 non-null    str
 18  grip_type            306 non-null    str
 19  string_pattern       309 non-null    str
 20  string_tension       303 non-null    str
 21  age                  47 non-null     str
 22  weight               3 non-null      str
 23  height               6 non-null      str
 24  other                5 non-null      str
 25  age_9-10             1 non-null      str
 26  strung _weight       2 non-null      str
dtypes: float64(3), str(24)
memory usage: 84.1 KB

## Examine each column

Below are the descriptive statistics for the numeric and object columns. Notice that some columns that *should* be numeric, like `head_size`, do not appear in the numeric columns' descriptive statistics. This is because all of the spec values were recorded as strings during scraping. 

**I will need to process those columns to convert them into float types**.

In [ ]:
# Numeric summary stats
raw_df.describe()

       racquet_rating  racquet_price  swingweight
count      264.000000     384.000000   306.000000
mean         4.745455     195.608021   316.679739
std          0.327303      93.015795    11.236156
min          2.700000      13.950000   270.000000
25%          4.600000     129.000000   310.250000
50%          4.800000     199.000000   318.000000
75%          5.000000     259.000000   325.000000
max          5.000000     619.000000   345.000000

In [18]:
# Object summary stats
raw_df.describe(include = ["object", "str"])

,racquet_url,racquet_img,racquet_name,racquet_description,head_size,length,strung_weight,balance,stiffness,beam_width,...,racquet_colors,grip_type,string_pattern,string_tension,age,weight,height,other,age_9-10,strung _weight
count,398,384,384,370,354,354,304,306,305,306,...,346,306,309,303,47,3,6,5,1,2
unique,398,384,378,363,43,21,31,76,22,87,...,72,42,36,23,10,3,5,3,1,1
top,https://www.tennis-warehouse.com/Babolat_Pure_...,https://img.tennis-warehouse.com/watermark/rs....,Prince Warrior 100 (300g),Easy power. Easy Spin. Great Price,100 in² / 645.16 cm²,27in / 68.58cm,11.4oz / 323g,13in / 33.02cm / 4 pts HL,66,23mm / 26mm / 23mm,...,Blue,Wilson Pro Performance,"16 Mains / 19 Crosses Mains skip: 7T,9T,7H,9H ...",50-60 pounds,9-10,8.1 ounces / 230 grams,45-49 inches / 114cm-124cm,String Tension:45-55 poundsSolinco recommends ...,9-10,11.1oz / 315g
freq,1,1,2,2,147,262,54,46,42,30,...,64,41,89,79,17,1,2,3,1,2

Just from the eye-test, there are several columns other than `head_size` that should be numeric. These include `length`, `strung weight`, `balance`, `stiffness`, `beam_width`, `string_pattern`, and `string_tension`. All of these columns (with the exception of `stiffness`)will need to be parsed/preprocessed before being able to be converted to numeric types. Below are the first 5 rows of the data for just those columns.

In [20]:
raw_df[["head_size", "length", "strung_weight", "balance", "stiffness", "beam_width", "string_pattern", "string_tension"]].head()

,head_size,length,strung_weight,balance,stiffness,beam_width,string_pattern,string_tension
0,100 in² / 645.16 cm²,27in / 68.58cm,11.2oz / 318g,12.99in / 32.99cm / 4 pts HL,66,23mm / 26mm / 23mm,"16 Mains / 19 Crosses Mains skip: 8T,8H Two Pi...",46-55 pounds
1,98 in² / 632.26 cm²,27in / 68.58cm,11.4oz / 323g,12.79in / 32.49cm / 6 pts HL,66,21mm / 23mm / 22mm,"16 Mains / 20 Crosses Mains skip: 7T,9T,7H,9H ...",46-55 pounds
2,98 in² / 632.26 cm²,27in / 68.58cm,11.4oz / 323g,12.79in / 32.49cm / 6 pts HL,66,21mm / 23mm / 22mm,"16 Mains / 20 Crosses Mains skip: 7T,9T,7H,9H ...",46-55 pounds
3,100 in² / 645.16 cm²,27.5in / 69.85cm,11.3oz / 320g,12.99in / 32.99cm / 6 pts HL,65,23mm / 26mm / 23mm,"16 Mains / 19 Crosses Mains skip: 8T,8H Two Pi...",46-55 pounds
4,100 in² / 645.16 cm²,27in / 68.58cm,10.6oz / 301g,13in / 33.02cm / 4 pts HL,66,23mm / 26mm / 23mm,"16 Mains / 19 Crosses Mains skip: 7T,9T,7H,9H ...",44-53 pounds

## Filter out junior racquets

There are two types of racquets in the data: regular racquets and junior racquets. My initial hunch is that the junior racquets are contributing to the NA values in the data. In the grand context of building a semantic search tool for tennis racquets, I think it is acceptable to exclude junior racquets. Semantic search aims to improve the shopping experience for tennis players who are able to semantically describe what they are looking for in a frame, which would mostly be passionate adult players or higher level juniors who are already using adult racquets.

Given this context, **I will filter out junior racquets from the dataset**.

In [52]:
# Create a new df without jr racquets
explore_df = raw_df.copy()
explore_df["is_junior"] = explore_df["racquet_name"].str.lower().str.contains("junior")

# Compare NA values between full and no jr datasets
ct_na_full = pd.Series(explore_df.isna().sum(), name = "ct_na_full")
pct_na_full = pd.Series(((ct_na_full / len(explore_df))).round(2), name = "pct_na_full")
ct_na_no_jr = pd.Series(explore_df[explore_df["is_junior"] == False].isna().sum(), name = "ct_na_no_jr")
pct_na_no_jr = pd.Series(((ct_na_no_jr / len(explore_df[explore_df["is_junior"] == False]))).round(2), name = "pct_na_no_jr")

na_comparison_df = pd.concat([ct_na_full, pct_na_full, ct_na_no_jr, pct_na_no_jr], axis = 1).reset_index(names = "column")

na_comparison_df["pct_pct_na_reduction"] = np.where(
    na_comparison_df["pct_na_full"] != na_comparison_df["pct_na_no_jr"],
    ((na_comparison_df["pct_na_full"] - na_comparison_df["pct_na_no_jr"]) / na_comparison_df["pct_na_full"]),
    0
)

As expected, removing Jr racquets reduces or completely eliminates NA values for the standard columns and actually boosts the "non-standard" spec columns to 100% NAs (indicating that those columns only exist for Jr racquets).

In [53]:
na_comparison_df.sort_values(by = "pct_pct_na_reduction", ascending = False)

,column,ct_na_full,pct_na_full,ct_na_no_jr,pct_na_no_jr,pct_pct_na_reduction
14,power_level,92,0.23,23,0.07,0.695652
10,swingweight,92,0.23,23,0.07,0.695652
16,swing_speed,92,0.23,23,0.07,0.695652
15,stroke_style,92,0.23,23,0.07,0.695652
12,beam_width,92,0.23,23,0.07,0.695652
11,stiffness,93,0.23,24,0.07,0.695652
9,balance,92,0.23,23,0.07,0.695652
18,grip_type,92,0.23,23,0.07,0.695652
19,string_pattern,89,0.22,23,0.07,0.681818
8,strung_weight,94,0.24,25,0.08,0.666667
20,string_tension,95,0.24,26,0.08,0.666667
17,racquet_colors,52,0.13,24,0.07,0.461538
7,length,44,0.11,23,0.07,0.363636
6,head_size,44,0.11,23,0.07,0.363636
13,composition,44,0.11,23,0.07,0.363636
3,racquet_rating,134,0.34,78,0.24,0.294118
24,other,393,0.99,324,0.98,0.010101
25,age_9-10,397,1.00,329,1.00,0.000000
26,strung _weight,396,0.99,327,0.99,0.000000
0,racquet_url,0,0.00,0,0.00,0.000000
1,racquet_img,14,0.04,14,0.04,0.000000
4,racquet_price,14,0.04,14,0.04,0.000000
2,racquet_name,14,0.04,14,0.04,0.000000
27,is_junior,0,0.00,0,0.00,0.000000
22,weight,395,0.99,329,1.00,-0.010101
23,height,392,0.98,329,1.00,-0.020408
21,age,351,0.88,329,1.00,-0.136364
5,racquet_description,28,0.07,28,0.09,-0.285714

## Takeaways and next steps


1. Get rid of all junior racquets from df

2. Add a racquet_brand column by extracting the brand name from racquet_name

3. Convert the following columns from object to float or int using regex or str logic:
    - Head Size
    - Length
    - Strung Weight
    - Balance
        - Create two columns: racquet_balance_in and racquet_balance_HH_HL
    - Stiffness
    - Beam width
    - String Pattern
        - Create two columns: racquet_mains and racquet_crosses
    - String Tension
        - Create two columns: racquet_tension_lower and racquet_tension_upper

Overall, the scraper did a decent job considering some of the oddities of the TW racquet pages. There are junior racquets present in the data, which aren't relevant and there are several columns that need to be processed into a different data type. 

Since the preprocessing required to fix these errors is relatively minimal, I've decided to use the scraper as-is and just quickly performing the basic preprocessing on the data afterwards.